repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: pipenv run ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: pipenv run ruff format
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: pyright
        entry: pipenv run pyright
        language: system
        types: [python]
        require_serial: true
