[tool.ruff]
select = ["ALL"]
ignore = [
    "D203",
    "D213",
    "COM812",
    "ISC001"
]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    "S101",
    "ARG",
    "FBT"
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.pytest.ini_options]
addopts = "--cov"

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
fail_under = 100
