[tool.ruff]
select = ["ALL"]
ignore = [
    "D203",
    "D213",
    "COM812",
    "ISC001",
    "FA102",
    "PLR2004",
    "PGH003"
]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    "S101",
    "ARG",
    "FBT",
    "D103"
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing"

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
fail_under = 100
